---
version: '0.2'
language: en,de-DE,it,es-ES
ignorePaths:
  - '**/node_modules/**'
  - '**/vscode_extension/**'
  - '**/.git/**'
  - '**/.pnpm-lock.json'
  - '**/pnpm-lock.yaml'
  - '**/yarn.lock'
  - dist/
  - out/
  - build/
  - .vscode
  - package-lock.json
  - megalinter-reports
  - .devcontainer/.dockerignore
  - .gitattributes
  - .gitignore
  - .prettierignore
  - CHANGELOG.md
  - LICENSE
  - '**/report/**'
  - '**/site/**'
  - '**/LICENSES/**'
  - '**/docs/about/EUPL-1.2.md'
  - cspell.config.yaml
files:
  - '*/**'
words:
  - checkconnct
  - jmuelbert
  - Jürgen
  - Mülbert
  - abbrs
  - adoc
  - aiohttp
  - arithmatex
  - Armin
  - armv
  - Codacy
  - codehilite
  - codeql
  - codelytv
  - colab
  - cpes
  - cyclonedx
  - DALL
  - devskim
  - dessant
  - esbenp
  - fsfe
  - glightbox
  - grype
  - htmlcov
  - htmlhintrc
  - inlinehilite
  - Italiano
  - Licence
  - linenums
  - linkcheckerrc
  - mkapi
  - mkautodoc
  - MKDOCS
  - mkdocstrings
  - mshick
  - ncipollo
  - ossar
  - ossf
  - Pintaldi
  - pkgs
  - pymdownx
  - returntocorp
  - rubocop
  - sarif
  - srggrs
  - Signup
  - stefanzweifel
  - tomwhross
  - unindexed
  - wagoid
  - xbps
  - xunit
flagWords:
  - hxe
maxNumberOfProblems: 1000
import: []
useGitignore: true
overrides:
  - filename: '**/de_DE/**'
    language: en,de
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: package.json
    ignoreWords:
      - color
      - cannot
allowCompoundWords: true
enableGlobDot: true
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript
dictionaryDefinitions:
  - name: ./project-words
    addWords: true
    scope:
      - workspace
    path: ./project-words.txt
dictionaries:
  - ./project-words
  - bash
  - companies
  - csharp
  - css
  - filetypes
  - fonts
  - misc
  - node
  - npm
  - powershell
  - python
  - software-terms
  - typescript
