---
# SPDX-FileCopyrightText: Free Software Foundation Europe
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: "REUSE Compliance Check"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release]

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can
    # default to all as well
    types: [opened, reopened, synchronize]
    # pull_request_target event is required for autolabeler to
    # support PRs from forks
    # pull_request_target:

permissions:
  contents: read

jobs:
  ReuseCheck:
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: "REUSE Compliance Check"
        uses: fsfe/reuse-action@a46482ca367aef4454a87620aa37c2be4b2f8106 # v3.0.0
